name: CI/CD
on:
 push:
  branches: [ main ]
 pull_request:
  branches: [ main ]
  
jobs:
 build:

  runs-on: ubuntu-latest
  
  strategy:
    matrix:
     node-version: [14.x]
   
  steps:
  - name: Checkout repository
    uses: actions/checkout@v2
 
  - name: Set up Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
     node-version: ${{ matrix.node-version }}
  
  - name: Install dependencies
    run: npm install
    
  - name: Installs cors
    run: npm install cors
    
  - name: Install dependencies in search app
    run: npm install --prefix search-app
    
  - name: Run npm test in search app
    run: npm test --prefix search-app

  - name: Run lint test
    run: npm run lint --prefix search-app

  - name: Build
    run: npm run build 
